name_or_path: ${oc.env:PWD}/../mend/models/Llama-3.2-1B-eos-sft
class_name: LlamaForCausalLM
edit_modules:
- model.layers.13.mlp.gate_proj
- model.layers.13.mlp.up_proj
- model.layers.13.mlp.down_proj
- model.layers.14.mlp.gate_proj
- model.layers.14.mlp.up_proj
- model.layers.14.mlp.down_proj
- model.layers.15.mlp.gate_proj
- model.layers.15.mlp.up_proj
- model.layers.15.mlp.down_proj
half: True