_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 11
                - 49
                - 50
                - 55
                - 71
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 55
                - 71
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.6
            "6": 4.46.3
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
data:
    value:
        batch_size: 32
        n_edits: 512
        name: zsre
        train_path: /data/users/zliu/malmen/malmen_data/zsre/zsre_train.json
        valid_path: /data/users/zliu/malmen/malmen_data/zsre/zsre_eval.json
editor:
    value:
        batch_size: 1024
        cache_dir: /data/users/zliu/malmen/cache
        load_checkpoint: false
        loc_coef: 1
        lr: 1e-06
        max_grad_norm: 1
        meta_lr: 1e-05
        n_blocks: 2
        n_epochs: 1
        name: malmen
        rank: 1920
        token: ans
editor_device:
    value: cuda:0
model:
    value:
        class_name: AutoModelForCausalLM
        edit_modules:
            - transformer.h.22.mlp.fc_out
            - transformer.h.23.mlp.fc_out
            - transformer.h.24.mlp.fc_out
            - transformer.h.25.mlp.fc_out
            - transformer.h.26.mlp.fc_out
            - transformer.h.27.mlp.fc_out
        half: true
        name_or_path: /home/zliu/shared_resources/models/gpt/gpt-j-6B
model_device:
    value: cuda:0
